package io.github.freshsupasulley.dbot;

import java.text.SimpleDateFormat;
import java.util.Date;

import com.google.gson.JsonElement;

import io.github.freshsupasulley.dbot.utils.JsonUtils;
import net.dv8tion.jda.api.JDA;
import net.dv8tion.jda.api.JDA.Status;
import net.dv8tion.jda.api.entities.Guild;
import net.dv8tion.jda.api.entities.Role;
import net.dv8tion.jda.api.entities.User;
import net.dv8tion.jda.api.entities.emoji.Emoji;
import net.dv8tion.jda.api.events.ExceptionEvent;
import net.dv8tion.jda.api.events.GatewayPingEvent;
import net.dv8tion.jda.api.events.guild.member.GuildMemberJoinEvent;
import net.dv8tion.jda.api.events.guild.member.GuildMemberRemoveEvent;
import net.dv8tion.jda.api.events.interaction.command.SlashCommandInteractionEvent;
import net.dv8tion.jda.api.events.session.SessionDisconnectEvent;
import net.dv8tion.jda.api.interactions.commands.build.OptionData;
import net.dv8tion.jda.api.requests.CloseCode;
import net.dv8tion.jda.api.utils.MarkdownSanitizer;

public class EventHandler extends GenericEventHandler {
	
	// 1 minute per tick
	private static final long TICK_TIME = 60000;
	private long lastTick;
	
	/** Allowed time to be disconnected before bot restarts */
	private static final long DOWNTIME_RESTART_THRESHOLD = 21600000;
	
	private long lastDisconnect = System.currentTimeMillis();
	
	public EventHandler(JDA jda)
	{
		super(jda);
		
		// Check during downtime if there's been any poll results generated by Discord
		// Limited by pagination but only grabbing 100 max should suffice
		jda.getGuildById(Main.SERVER_ID).getTextChannelById(Main.VOTING_BOOTH).getHistoryFromBeginning(100).queue(history ->
		{
			history.getRetrievedHistory().forEach(message ->
			{
				// Check for polls
				Main.server.checkMessageForPollResult(message);
			});
		}, error -> Main.log.error("Failed to collect messages on startup for poll checking", error));
	}
	
	/**
	 * Ticks the server object and verifies server data is kept up to date.
	 */
	@Override
	public void onGatewayPing(GatewayPingEvent event)
	{
		if(System.currentTimeMillis() - lastTick > TICK_TIME)
		{
			// Check if server data changed
			try
			{
				JsonElement data = JsonUtils.parse(Main.readServerData());
				JsonElement current = JsonUtils.parse(Main.server.toString());
				
				if(!data.equals(current))
				{
					Main.log.info("Stored server data:\n{}\nServer object data:\n{}", data, current);
					throw new IllegalStateException("Stored server data and server object data do not match");
				}
			} catch(Exception e)
			{
				Main.log.error("JSON data does not match! You failed to update the server data somewhere", e);
				Main.updateServerData();
			}
			
			lastTick = System.currentTimeMillis();
			
			// If not connected
			if(event.getJDA().getStatus() != Status.CONNECTED)
			{
				long downtime = System.currentTimeMillis() - lastDisconnect;
				
				if(downtime >= DOWNTIME_RESTART_THRESHOLD)
				{
					Main.log.error("Down for {}ms (over the allowed downtime threshold). Rebooting...", downtime);
					PrivateHandler.reboot();
				}
			}
			// Only tick server if we're online
			else
			{
				Main.server.tick(event.getJDA());
			}
		}
	}
	
	private void slashCommand(SlashCommandInteractionEvent event)
	{
		if(!event.isFromGuild())
		{
			event.reply("DM commands are not supported. Use " + Main.BOT_NAME + " in Discordias.").setEphemeral(true).queue();
			return;
		}
		
		JDA jda = event.getJDA();
		
		// Message content
		User user = event.getUser();
		Guild guild = event.getGuild();
		
		// Don't acknowledge if we're in test channel
		if(!Main.inIDE && event.getChannel().getIdLong() == Main.TEST_CHANNEL)
		{
			Main.log.info("Ignoring test channel command");
			return;
		}
		
		ServerMember sender = Main.server.getMember(user);
		
		Main.log.info("[SLASH COMMAND (" + guild.getId() + ", channel #" + event.getChannel().getId() + ") - '" + user.getName() + "']: \"" + event.getCommandString() + "\"");
		
		switch(event.getFullCommandName())
		{
			// bad idea. just make an "anti-baby-raging" role
//			case "timeout":
//			{
//				if(!DMain.server.isPresident(sender))
//				{
//					event.reply("Only the President can use this command").queue();
//					return;
//				}
//				
//				if(DMain.server.isElectionActive())
//				{
//					event.reply("Baby raging prohibited");
//					return;
//				}
//				
//				Map<String, Integer> multipliers = Map.of("minutes", 1, "hours", 60, "days", 1440);
//				
//				long totalMinutes = multipliers.entrySet().stream().mapToLong(entry ->
//				{
//					OptionMapping opt = event.getOption(entry.getKey());
//					return (opt != null ? opt.getAsInt() : 0) * entry.getValue();
//				}).sum();
//				
//				if(totalMinutes > Member.MAX_TIME_OUT_LENGTH * 1440L)
//				{
//					event.reply("Can't timeout a member for more than " + Member.MAX_TIME_OUT_LENGTH + " days").queue();
//				}
//				else
//				{
//					event.getOption("user", option -> option.getAsMember()).timeoutFor(totalMinutes, TimeUnit.MINUTES).queue();
//					event.reply("Timed out <@" + user.getId() + "> for " + totalMinutes + " minute(s)").queue();
//				}
//				
//				break;
//			}
//			case "kick":
//			{
//				if(!DMain.server.isPresident(sender))
//				{
//					event.reply("Only the President can use this command").queue();
//					return;
//				}
//				
//				if(DMain.server.isElectionActive())
//				{
//					event.reply("Baby raging prohibited");
//					return;
//				}
//				
//				event.getOption("user", option -> option.getAsMember());
//				
//				break;
//			}
			case "campaign":
			{
				// Don't allow new lines
				// Do not use escape here because \n would look ugly as hell
				String slogan = MarkdownSanitizer.sanitize(event.getOption("slogan").getAsString()).replace('\n', ' ').replace('\t', ' ');
				
				if(Main.server.isPresident(sender))
				{
					if(Main.server.isLastTerm())
					{
						event.reply("You cannot be elected President for more than two terms at a time.").queue();
						return;
					}
					else
					{
						event.reply("The President automatically runs for re-election once voting begins.").queue();
						return;
					}
				}
				
				// You can only campaign when the presidential vote poll is live
				if(!Main.server.isElectionActive())
				{
					float daysRemaining = Main.server.millisRemainingInTerm() / 8.64e+7f;
					event.reply("Polls for the **" + Server.ordinal(Main.server.getPresidentialCount() + 1) + " Presidential Election** open **" + getExactTime(System.currentTimeMillis() + Main.server.millisRemainingInTerm() - Server.PRESIDENTIAL_VOTE_TIME) + " EST**. The President has " + (int) (daysRemaining) + " day" + ((int) daysRemaining != 1 ? "s" : "") + " and " + (int) (daysRemaining % 1 * 24) + " hours left in office. You will be notified in <#" + Main.VOTING_BOOTH + "> when the election begins.").queue();
				}
				else if(Main.server.getCandidates().size() == 10)
				{
					event.reply("There are too many candidates running for office. Only 10 at a time.").queue();
				}
				else if(slogan.length() > Math.min(200, OptionData.MAX_STRING_OPTION_LENGTH))
				{
					// Just in case it changes but totally unnecessary
					event.reply("Slogan must be less than " + Math.min(200, OptionData.MAX_STRING_OPTION_LENGTH) + " characters.").setEphemeral(true).queue();
				}
				else
				{
					// Check if already campaigning
					for(Candidate candidate : Main.server.getCandidates())
					{
						if(candidate.getID() == sender.getID())
						{
							event.reply("You're already campaigning!").queue();
							return;
						}
					}
					
					Role party = event.getOption("party").getAsRole();
					Main.server.getCandidates().add(new Candidate(Main.server.getNextCandidateSlot(), user.getIdLong(), slogan, party));
					
					// Add reactions
					for(int i = 0; i < Main.server.getCandidates().size(); i++)
					{
						if(i != 9)
						{
							Main.server.getPresidentialVote(jda).addReaction(Emoji.fromUnicode("U+3" + (i + 1) + "U+fe0fU+20e3")).queue();
						}
						else
						{
							Main.server.getPresidentialVote(jda).addReaction(Emoji.fromUnicode("U+1f51f")).queue();
						}
					}
					
					Main.server.updatePresidentialVote(jda);
					event.reply("You are now campaigning! Check the Presidential Voting poll in <#" + Main.VOTING_BOOTH + ">.").queue();
				}
				
				return;
			}
			case "slogan":
			{
				String content = MarkdownSanitizer.sanitize(event.getOption("slogan").getAsString());
				
				if(Main.server.isPresident(sender))
				{
					Main.server.setPresidentialSlogan(content);
					event.reply("Updated your slogan, Mr. President" + Main.server.getPresidentialVote(jda) == null ? ". You will see it during the next election" : "").queue();
					return;
				}
				
				if(Main.server.getPresidentialVote(jda) == null)
				{
					event.reply("There is no active presidential election").queue();
					return;
				}
				// Check if already campaigning
				for(Candidate candidate : Main.server.getCandidates())
				{
					if(candidate.getID() == sender.getID())
					{
						candidate.setSlogan(content);
						Main.server.updatePresidentialVote(jda);
						event.reply("Updated your slogan to \"" + content + "\"").queue();
						return;
					}
				}
				
				event.reply("You're not campaigning! Use " + Main.getCommandReference("campaign") + " to register").queue();
				return;
			}
			case "next-election":
			{
				if(Main.server.getPresidentialVote(jda) != null)
				{
					event.reply("The current election will end at **" + getExactTime(System.currentTimeMillis() + Main.server.millisRemainingInTerm()) + " EST**.").queue();
				}
				else
				{
					event.reply("The next election opens on **" + getExactTime(System.currentTimeMillis() + Main.server.millisRemainingInTerm() - Server.PRESIDENTIAL_VOTE_TIME) + " EST**.").queue();
				}
				
				return;
			}
			case "propose":
			{
				String content = event.getOption("amendment").getAsString();
				content = MarkdownSanitizer.escape(content); // escape, not sanitize. Allows people to type * instead of removing it
				
				// Add the poll
				Main.server.beginPoll(event, new ProposePoll(jda.getTextChannelById(Main.VOTING_BOOTH), content));
				break;
			}
			case "repeal":
			{
				int number = event.getOption("amendment-number").getAsInt();
				
				if(number < 1 || number > Main.server.getAmendments())
				{
					event.reply("Enter a number between 1 - " + Main.server.getAmendments()).setEphemeral(true).queue();
					break;
				}
				
				// Add the poll
				Main.server.beginPoll(event, new RepealPoll(jda.getTextChannelById(Main.VOTING_BOOTH), number));
				break;
			}
			case "impeach":
			{
				// Don't allow impeachment if it will overlap with the presidential vote
				ImpeachPoll poll = new ImpeachPoll(jda.getTextChannelById(Main.VOTING_BOOTH), event.getOption("reason").getAsString());
				
				if(Main.server.millisRemainingInTerm() - Server.PRESIDENTIAL_VOTE_TIME < poll.getVoteTime().toMillis())
				{
					if(Main.server.getPresidentialVote(jda) == null)
					{
						event.reply("Impeachment disabled. The polls open **" + getExactTime(System.currentTimeMillis() + Main.server.millisRemainingInTerm() - Server.PRESIDENTIAL_VOTE_TIME) + " EST.**").queue();
					}
					else
					{
						event.reply("Impeachment disabled. An election is active").queue();
					}
					
					break;
				}
				
				// Add the poll
				Main.server.beginPoll(event, poll);
				break;
			}
//			case "secret":
//			{
//				String word = event.getOption("word").getAsString().trim();
//				String response = event.getOption("response").getAsString().trim();
//				
//				DMain.server.addSecret(word, response);
//				
//				event.reply("\"" + word + "\" is now a secret command (will send " + response + ")").queue();
//				return;
//			}
//			case "all-secrets":
//			{
//				event.reply(DMain.server.getSecretCommands().keySet().stream().sorted().collect(Collectors.joining(", "))).queue();
//				return;
//			}
//			case "unsecret":
//			{
//				String word = event.getOption("word").getAsString();
//				
//				// If success
//				if(DMain.server.unsecret(word))
//				{
//					event.reply("Removed \"" + MarkdownSanitizer.sanitize(word) + "\" from secret commands").queue();
//				}
//				else
//				{
//					event.reply("\"" + MarkdownSanitizer.sanitize(word) + "\" isn't a secret command").queue();
//				}
//				
//				return;
//			}
//			case "resecret":
//			{
//				String word = event.getOption("word").getAsString();
//				
//				if(DMain.server.resecretSecret(word))
//				{
//					event.reply("Resecreted \"" + MarkdownSanitizer.sanitize(word) + "\"").queue();
//				}
//				else
//				{
//					event.reply("\"" + MarkdownSanitizer.sanitize(word) + "\" isn't an unsecreted command").queue();
//				}
//				
//				return;
//			}
			default:
			{
				Main.log.error("Unhandled command {}", event.getName());
				event.reply("This command is under construction :hammer: :construction:").queue();
				return;
			}
		}
	}
	
	@Override
	public void onSlashCommandInteraction(SlashCommandInteractionEvent event)
	{
		// Handle any errors
		try
		{
			slashCommand(event);
		} catch(Throwable t)
		{
			if(!event.isAcknowledged())
				event.reply(Main.ERROR_MSG).queue();
			Main.log.error("An error occured in command handling", t);
		}
	}
	
//	@Override
//	public void onGuildMessageReceived(MessageReceivedEvent event)
//	{
//		DMain.server.checkMessageForPollResult(event.getMessage());
//		
//		// BEYOND THIS POINT IS ONLY SECRET COMMANDS
//		if(event.getAuthor().isBot() || DMain.SERVER_ID != event.getGuild().getIdLong() || !event.isFromType(ChannelType.TEXT))
//			return;
//		
//		// Get user
//		TextChannel channel = event.getChannel().asTextChannel();
//		
//		// Handle server command requests
//		String message = event.getMessage().getContentDisplay().replaceAll("\n", "");
//		
//		// Secret commands
//		if(channel.getParentCategory() == null || channel.getParentCategory().getIdLong() == DMain.THE_WHITE_HOUSE_CATEGORY || channel.getParentCategory().getIdLong() == DMain.MAGNA_FARTA_CATEGORY)
//			return;
//		if(message.contains("http"))
//			return;
//			
//		// boolean canReact = eventMessage.getGuild().getSelfMember().hasPermission(Permission.MESSAGE_ADD_REACTION);
//		// int numReacts = 0;
//		StringBuilder builder = new StringBuilder();
//		Map<String, String> commands = new HashMap<String, String>();
//		
//		// For each key (word)
//		for(String key : DMain.server.getSecretCommands().keySet())
//		{
//			// If it CONTAINS, not equals
//			if(message.toLowerCase().contains(key.toLowerCase()))
//			{
//				String[] values = DMain.server.getSecretCommands().get(key).split("\n");
//				// Pick random link
//				String value = values[(int) (Math.random() * values.length)];
//				
//				// +1 for break character
//				if(builder.length() + value.length() + 1 > Message.MAX_CONTENT_LENGTH)
//					break;
//				
//				// Append command
//				builder.append(value + "\n");
//				commands.put(key, value);
//				//
//				// if(canReact && numReacts < Message.MAX_REACTIONS)
//				// {
//				// numReacts++;
//				// eventMessage.addReaction(Emoji.fromUnicode(unicode)).queue();
//				// }
//			}
//		}
//		
//		// This can happen believe it or not (user can make a poll and then this blows tf up)
//		if(builder.toString().isEmpty())
//			return;
//		
//		event.getChannel().sendMessage(builder.toString()).queue(queued ->
//		{
//			// Wait before getting the new message
//			event.getChannel().retrieveMessageById(queued.getId()).queueAfter(3, TimeUnit.SECONDS, success ->
//			{
//				boolean modified = false;
//				
//				// For each secret
//				for(Entry<String, String> set : commands.entrySet())
//				{
//					String key = set.getKey();
//					String link = set.getValue();
//					
//					// If that secret is a link (trying to be an embed)
//					if(link.contains("http"))
//					{
//						boolean found = false;
//						
//						// Check if that link actually embedded properly
//						for(MessageEmbed embed : success.getEmbeds())
//						{
//							String url = embed.getUrl();
//							
//							if(url.equals(link))
//							{
//								found = true;
//								break;
//							}
//						}
//						
//						if(!found)
//						{
//							modified = true;
//							DMain.log.info("Removing {} from secret commands. Embed didn't work at {}", key, link);
//							DMain.server.getSecretCommands().remove(key);
//							
//							// If it was just one secret command, just delete the message
//							if(commands.size() == 1)
//							{
//								success.delete().queue();
//							}
//						}
//					}
//				}
//				
//				if(modified)
//				{
//					DMain.updateServerData();
//				}
//			});
//		});
//	}
	
	@Override
	public void onGuildMemberJoin(GuildMemberJoinEvent event)
	{
		Main.log.info(event.getUser().getName() + " " + event.getUser().getIdLong() + " joined!");
	}
	
	@Override
	public void onGuildMemberRemove(GuildMemberRemoveEvent event)
	{
		Main.server.removeMember(event.getJDA(), event.getUser().getIdLong());
		Main.log.info("{} ({}) left the server ", event.getUser().getEffectiveName(), event.getUser().getId());
	}
	
	@Override
	public void onSessionDisconnect(SessionDisconnectEvent event)
	{
		CloseCode code = event.getCloseCode();
		Main.log.info("DISCONNECTED! Close code: " + (code == null ? "null" : code.getCode() + ". Meaning: " + code.getMeaning()) + ". Closed by discord: " + event.isClosedByServer());
		lastDisconnect = System.currentTimeMillis();
	}
	
	@Override
	public void onException(ExceptionEvent event)
	{
		Main.log.error("JDA Exception! Response code: {}, logged: {}, cause: {}, #{}", event.getResponseNumber(), event.isLogged(), event.getCause(), event.getResponseNumber());
	}
	
	private String getExactTime(long time)
	{
		return new SimpleDateFormat("MM/dd/yyyy h:mm aa").format(new Date(time));
	}
}
