package io.github.freshsupasulley.dbot;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.AbstractMap;
import java.util.ArrayList;
import java.util.Date;
import java.util.EnumSet;
import java.util.List;
import java.util.Set;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.atomic.AtomicReference;

import javax.annotation.Nullable;

import com.google.gson.JsonElement;

import io.github.freshsupasulley.dbot.polls.ImpeachPoll;
import io.github.freshsupasulley.dbot.polls.NaturalizePoll;
import io.github.freshsupasulley.dbot.polls.ProposePoll;
import io.github.freshsupasulley.dbot.polls.RepealPoll;
import io.github.freshsupasulley.dbot.utils.JsonUtils;
import net.dv8tion.jda.api.EmbedBuilder;
import net.dv8tion.jda.api.JDA;
import net.dv8tion.jda.api.JDA.Status;
import net.dv8tion.jda.api.Permission;
import net.dv8tion.jda.api.entities.Guild;
import net.dv8tion.jda.api.entities.Member;
import net.dv8tion.jda.api.entities.Role;
import net.dv8tion.jda.api.entities.User;
import net.dv8tion.jda.api.entities.channel.concrete.Category;
import net.dv8tion.jda.api.entities.channel.concrete.TextChannel;
import net.dv8tion.jda.api.entities.channel.concrete.VoiceChannel;
import net.dv8tion.jda.api.entities.channel.middleman.GuildChannel;
import net.dv8tion.jda.api.entities.emoji.Emoji;
import net.dv8tion.jda.api.events.ExceptionEvent;
import net.dv8tion.jda.api.events.GatewayPingEvent;
import net.dv8tion.jda.api.events.guild.member.GuildMemberJoinEvent;
import net.dv8tion.jda.api.events.guild.member.GuildMemberRemoveEvent;
import net.dv8tion.jda.api.events.interaction.command.SlashCommandInteractionEvent;
import net.dv8tion.jda.api.events.message.MessageReceivedEvent;
import net.dv8tion.jda.api.events.session.SessionDisconnectEvent;
import net.dv8tion.jda.api.interactions.commands.OptionMapping;
import net.dv8tion.jda.api.interactions.commands.build.OptionData;
import net.dv8tion.jda.api.requests.CloseCode;
import net.dv8tion.jda.api.utils.MarkdownSanitizer;

public class EventHandler extends GenericEventHandler {
	
	private static final String BAD_HEX_RESPONSE = "Invalid hex color code. Click [here](<https://rgbcolorcode.com>) for a generator";
	
	// 1 minute per tick
	private static final long TICK_TIME = 60000;
	private long lastTick;
	
	/** Allowed time to be disconnected before bot restarts */
	private static final long DOWNTIME_RESTART_THRESHOLD = 21600000;
	
	private long lastDisconnect = System.currentTimeMillis();
	
	public EventHandler(JDA jda)
	{
		super(jda);
		
		// Check during downtime if there's been any poll results generated by Discord
		// Limited by pagination but only grabbing 100 max should suffice
		jda.getGuildById(Main.SERVER_ID).getTextChannelById(Main.VOTING_BOOTH).getHistoryFromBeginning(100).submit().thenAccept(history ->
		{
			history.getRetrievedHistory().forEach(message ->
			{
				// Check for polls
				Main.server.checkMessageForPollResult(message);
			});
		}).exceptionally(error ->
		{
			Main.log.error("Failed to collect messages on startup for poll checking", error);
			return null;
		});
	}
	
	/**
	 * Ticks the server object and verifies server data is kept up to date.
	 */
	@Override
	public void onGatewayPing(GatewayPingEvent event)
	{
		if(System.currentTimeMillis() - lastTick > TICK_TIME)
		{
			// Check if server data changed
			try
			{
				JsonElement data = JsonUtils.parse(Main.readServerData());
				JsonElement current = JsonUtils.parse(Main.server.toString());
				
				if(!data.equals(current))
				{
					Main.log.info("Stored server data:\n{}\nServer object data:\n{}", data, current);
					throw new IllegalStateException("Stored server data and server object data do not match");
				}
			} catch(Exception e)
			{
				Main.log.error("JSON data does not match! You failed to update the server data somewhere", e);
				Main.updateServerData();
			}
			
			lastTick = System.currentTimeMillis();
			
			// If not connected
			if(event.getJDA().getStatus() != Status.CONNECTED)
			{
				long downtime = System.currentTimeMillis() - lastDisconnect;
				
				if(downtime >= DOWNTIME_RESTART_THRESHOLD)
				{
					Main.log.error("Down for {}ms (over the allowed downtime threshold). Rebooting...", downtime);
					PrivateHandler.reboot();
				}
			}
			// Only tick server if we're online
			else
			{
				Main.server.tick(event.getJDA());
			}
		}
	}
	
	@Override
	public void onGuildMessageReceived(MessageReceivedEvent event)
	{
		super.onGuildMessageReceived(event);
		Main.server.checkMessageForPollResult(event.getMessage());
	}
	
	private void slashCommand(SlashCommandInteractionEvent event)
	{
		if(!event.isFromGuild())
		{
			event.reply("DM commands are not supported. Use " + Main.BOT_NAME + " in Discordias.").setEphemeral(true).queue();
			return;
		}
		
		JDA jda = event.getJDA();
		
		// Message content
		User user = event.getUser();
		Guild guild = event.getGuild();
		
		// Don't acknowledge if we're in test channel
		if(!Main.inIDE && event.getChannel().getIdLong() == Main.TEST_CHANNEL)
		{
			Main.log.info("Ignoring test channel command");
			return;
		}
		
		ServerMember sender = Main.server.getMember(event.getMember());
		
		Main.log.info("[SLASH COMMAND (" + guild.getId() + ", channel #" + event.getChannel().getId() + ") - '" + user.getName() + "']: \"" + event.getCommandString() + "\"");
		
		// Check if naturalized
		if(!Main.server.isNaturalized(event.getMember()))// && Main.OWNER_ID != event.getMember().getIdLong())
		{
			event.reply("You aren't a citizen! You need to be naturalized before you can use " + Main.BOT_NAME + " commands. Ask a citizen to start a naturalization poll!").queue();
			return;
		}
		
		switch(event.getName())
		{
			case "party":
			{
				// If this is a subcommand group, it's guaranteed to be edit (at least right now)
				if(event.getSubcommandGroup() != null)
				{
					// ENTER EDIT SUBCOMMAND!
					PoliticalParty party = sender.getPoliticalParty();
					
					// Ensure this is the party leader
					if(party == null)
					{
						event.reply("You aren't in a party").queue();
						break;
					}
					
					if(sender.getID() != party.getLeaderID())
					{
						event.reply("You are not the party leader (<@" + party.getLeaderID() + "> is)").setAllowedMentions(Set.of()).queue();
						break;
					}
					
					switch(event.getSubcommandName())
					{
						case "name":
						{
							String name = event.getOption("name").getAsString();
							
							if(Main.server.partyNameCollision(guild, name))
							{
								event.reply("There's already a party with that name").queue();
								break;
							}
							
							// Rename the role
							guild.getRoleById(party.getRole()).getManager().setName(name).submit().thenCompose(entry ->
							{
								// Rename the category
								Category category = guild.getCategoryById(party.getCategory());
								return category.getManager().setName(name).submit().thenApply(__ -> category);
							}).thenCompose(category ->
							{
								List<CompletableFuture<Void>> renameFutures = new ArrayList<>();
								
								for(GuildChannel channel : category.getChannels())
								{
									String newChannelName;
									
									if(channel instanceof TextChannel)
									{
										newChannelName = name.toLowerCase() + " chat";
									}
									else if(channel instanceof VoiceChannel)
									{
										newChannelName = name.toLowerCase() + " voice";
									}
									else
									{
										// Skip unknown types
										continue;
									}
									
									renameFutures.add(channel.getManager().setName(newChannelName).submit());
								}
								
								return CompletableFuture.allOf(renameFutures.toArray(CompletableFuture[]::new));
							}).thenRun(() ->
							{
								event.reply("Changed party name to **" + MarkdownSanitizer.escape(name) + "**").queue();
							}).exceptionally(e ->
							{
								Main.log.error("Failed to rename party artifacts", e);
								event.reply(Main.ERROR_MSG).queue();
								return null;
							});
							
							break;
						}
						case "color":
						{
							Color color = validateHex(event.getOption("color").getAsString());
							
							if(color == null)
							{
								event.reply(BAD_HEX_RESPONSE).queue();
								break;
							}
							
							guild.getRoleById(party.getRole()).getManager().setColor(color).queue(done ->
							{
								event.reply("Changed party color").queue();
							}, e ->
							{
								event.reply(Main.ERROR_MSG).queue();
							});
							
							break;
						}
						case "ban":
						{
							Member member = event.getOption("user").getAsMember();
							
							if(member == null)
							{
								event.reply("Unknown member").queue();
								break;
							}
							
							if(party.addBan(member))
							{
								if(!isBot(member))
								{
									sender.setPoliticalParty(null);
								}
								
								Main.updateServerData();
								
								guild.removeRoleFromMember(user, guild.getRoleById(party.getRole())).queue(done ->
								{
									event.reply("Banned <@" + member.getIdLong() + "> from <@&" + party.getRole() + ">").setAllowedMentions(Set.of()).queue();
								}, e ->
								{
									Main.log.error("Failed to leave party", e);
									event.reply(Main.ERROR_MSG).queue();
								});
							}
							else
							{
								event.reply("<@" + member.getIdLong() + "> is already banned").queue();
							}
							
							break;
						}
						case "unban":
						{
							Member member = event.getOption("user").getAsMember();
							
							if(member == null)
							{
								event.reply("Unknown member").queue();
								break;
							}
							
							if(party.removeBan(member))
							{
								Main.updateServerData();
								event.reply("Unbanned <@" + member.getIdLong() + "> from <@&" + party.getRole() + ">").setAllowedMentions(Set.of()).queue();
							}
							else
							{
								event.reply("<@" + member.getIdLong() + "> isn't banned").queue();
							}
							
							break;
						}
						case "invite-bot":
						{
							Member member = event.getOption("bot").getAsMember();
							
							if(member == null)
							{
								event.reply("Unknown member").queue();
								break;
							}
							
							// Ensure user is a bot
							if(!isBot(member))
							{
								event.reply("<@" + member.getId() + "> is not a bot").setAllowedMentions(Set.of()).queue();
								break;
							}
							
							// Might as well check for this
							if(party.isBanned(member))
							{
								event.reply("<@" + member.getId() + "> is banned!").setAllowedMentions(Set.of()).queue();
								break;
							}
							
							// If this bot already has a role
							if(member.getRoles().stream().anyMatch(role -> role.getIdLong() == party.getRole()))
							{
								event.reply("<@" + member.getId() + "> is already a party member").setAllowedMentions(Set.of()).queue();
								break;
							}
							
							// Add role to bot
							guild.addRoleToMember(member, guild.getRoleById(party.getRole())).queue(success ->
							{
								event.reply("Added <@" + member.getId() + "> to <@&" + party.getRole() + ">").setAllowedMentions(Set.of()).queue();
							}, e ->
							{
								event.reply(Main.ERROR_MSG).queue();
							});
							
							break;
						}
						case "transfer":
						{
							Member member = event.getOption("user").getAsMember();
							
							// I specified OptionType.USER, but apparently that can return a user that's not in this guild? Idk, just a safety net
							if(member == null)
							{
								Main.log.error("Mentioned {}, but that apparently isn't a member...?", member);
								event.reply("Unknown user").queue();
								break;
							}
							
							if(isBot(member))
							{
								event.reply("Bots don't have rights :robot:").queue();
								break;
							}
							
							// Check if member is part of the leader's party
							ServerMember mentioned = Main.server.getMember(member);
							
							// There's a null check in .equals dw
							if(!party.equals(mentioned.getPoliticalParty()))
							{
								event.reply("That user isn't a member of your party").queue();
								break;
							}
							
							// Stop from transferring to themselves
							if(mentioned.getID() == sender.getID())
							{
								event.reply("You're already the leader").queue();
								return;
							}
							
							// Transfer ownership
							mentioned.getPoliticalParty().setLeader(mentioned.getID());
							Main.updateServerData();
							event.reply("Transferred leadership of your party to <@" + mentioned.getID() + ">").queue();
							break;
						}
					}
				}
				// General party commands (non-edit)
				else
				{
					switch(event.getSubcommandName())
					{
						case "create":
						{
							// Check if already in a party
							if(sender.getPoliticalParty() != null)
							{
								event.reply("Leave your political party before creating one").queue();
								return;
							}
							
							String name = event.getOption("name").getAsString();
							
							if(Main.server.partyNameCollision(guild, name))
							{
								event.reply("There's already a party with that name").queue();
								return;
							}
							
							int randomColor = (int) (Math.random() * 0x1000000); // generate a default hex if not provided (color is optional)
							Color color = validateHex(event.getOption("color", String.format("%06X", randomColor), OptionMapping::getAsString));
							
							if(color == null)
							{
								event.reply(BAD_HEX_RESPONSE).queue();
								break;
							}
							
							// Creating a party could take a while
							event.deferReply().queue();
							
							// Begin party creation!
							AtomicReference<Role> createdRole = new AtomicReference<>();
							AtomicReference<Category> createdCategory = new AtomicReference<>();
							List<GuildChannel> createdChannels = new ArrayList<>();
							
							guild.createRole().setName(name).setColor(color).submit().thenCompose(role ->
							{
								createdRole.set(role);
								// Hoist it above citizen so the colors show
								int targetIndex = 2;
								return guild.modifyRolePositions().selectPosition(role).moveTo(targetIndex).submit().thenApply(__ -> role);
							}).thenCompose(role ->
							{
								return guild.addRoleToMember(user, role).submit().thenApply(__ -> role);
								// Hoist the category about general probably
							}).thenCompose(role -> guild.createCategory(role.getName()).setPosition(2).addPermissionOverride(guild.getRoleById(Main.THE_PRESIDENT_ID), null, EnumSet.of(Permission.MANAGE_CHANNEL)).addPermissionOverride(role, EnumSet.of(Permission.VIEW_CHANNEL), null).addPermissionOverride(guild.getPublicRole(), null, EnumSet.of(Permission.VIEW_CHANNEL)).submit().thenApply(category ->
							{
								createdCategory.set(category);
								return new AbstractMap.SimpleEntry<>(role, category);
							})).thenCompose(entry ->
							{
								Role role = entry.getKey();
								Category category = entry.getValue();
								
								// Create text and voice channels
								// This works! Discord sanitizes the channel names
								CompletableFuture<Void> textFuture = guild.createTextChannel(role.getName() + " chat", category).addPermissionOverride(guild.getRoleById(Main.THE_PRESIDENT_ID), null, EnumSet.of(Permission.MANAGE_CHANNEL)).addPermissionOverride(role, EnumSet.of(Permission.VIEW_CHANNEL), null).addPermissionOverride(role, EnumSet.of(Permission.VIEW_CHANNEL), null).addPermissionOverride(guild.getPublicRole(), null, EnumSet.of(Permission.VIEW_CHANNEL)).submit().thenAccept(channel -> createdChannels.add(channel));
								CompletableFuture<Void> voiceFuture = guild.createVoiceChannel(role.getName() + " voice", category).addPermissionOverride(guild.getRoleById(Main.THE_PRESIDENT_ID), null, EnumSet.of(Permission.MANAGE_CHANNEL)).addPermissionOverride(role, EnumSet.of(Permission.VIEW_CHANNEL), null).addPermissionOverride(role, EnumSet.of(Permission.VIEW_CHANNEL), null).addPermissionOverride(guild.getPublicRole(), null, EnumSet.of(Permission.VIEW_CHANNEL)).submit().thenAccept(channel -> createdChannels.add(channel));
								
								return CompletableFuture.allOf(textFuture, voiceFuture);
							}).thenRun(() ->
							{
								// Create the party and set the sender to be a member of it
								PoliticalParty party = new PoliticalParty(createdRole.get().getIdLong(), createdCategory.get().getIdLong(), user.getIdLong());
								Main.server.createPoliticalParty(party);
								sender.setPoliticalParty(party);
								Main.updateServerData();
								
								event.getHook().sendMessage("Congratulations! :tada: You are now the proud leader of the <@&" + createdRole.get().getId() + "> party!").setAllowedMentions(Set.of()).queue();
							}).exceptionally(e ->
							{
								Main.log.error("Party creation failed", e);
								event.getHook().sendMessage(Main.ERROR_MSG).queue();
								
								// Rollback in reverse order (order probably doesn't matter tho)
								for(GuildChannel channel : createdChannels)
								{
									channel.delete().queue();
								}
								
								if(createdCategory.get() != null)
								{
									createdCategory.get().delete().queue();
								}
								
								if(createdRole.get() != null)
								{
									createdRole.get().delete().queue();
								}
								
								return null;
							});
							
							// guild.createRole().setName(name + " Party").setColor(color).submit().thenCompose(role -> guild.addRoleToMember(user, role).submit().thenApply(unused ->
							// role)).thenAccept(role ->
							// {
							// // We succeeded
							// event.reply("Congratulations :tada:! You are now the proud owner of the <@&" + role.getId() + "> party!").queue(); // its ok to ping the role here because
							// the party was just made (no one to ping)
							// Main.server.createPoliticalParty(role, user);
							// Main.updateServerData();
							// }).exceptionally(e ->
							// {
							// Main.log.error("Failed to create political party", e);
							// event.reply(Main.ERROR_MSG).queue();
							// return null;
							// });
							
							break;
						}
						case "join":
						{
							Role role = event.getOption("party").getAsRole();
							
							// If the user is already in a political party
							if(sender.getPoliticalParty() != null)
							{
								event.reply(role.getIdLong() == sender.getPoliticalParty().getRole() ? "You're already in this party" : "You already belong to a party").queue();
								return;
							}
							
							PoliticalParty party = Main.server.getParty(role.getIdLong());
							
							// If the role mentioned is an actual political party
							if(party == null)
							{
								event.reply("That role isn't a political party").queue();
								return;
							}
							
							// Check if the member is banned
							if(party.isBanned(event.getMember()))
							{
								event.reply("You're banned from <@&" + party.getRole() + ">!").setAllowedMentions(Set.of()).queue();
								return;
							}
							
							// this might be unnecessary
							// Check if they already have the role they mentioned
							// if(guild.getMemberById(user.getId()).getRoles().stream().anyMatch(role -> role.getId().equals(party.getId())))
							// {
							// event.reply("You're already in this party!").queue();
							// return;
							// }
							
							guild.addRoleToMember(user, role).queue(done ->
							{
								// id rather not mention roles in order to avoid pinging the entire party
								event.reply("Joined <@&" + role.getId() + ">").setAllowedMentions(Set.of()).queue();
								sender.setPoliticalParty(party);
								Main.updateServerData();
							}, e ->
							{
								Main.log.error("Failed to join political party", e);
								event.reply(Main.ERROR_MSG).queue();
							});
							
							break;
						}
						case "leave":
						{
							if(sender.getPoliticalParty() == null)
							{
								event.reply("You're not in a party!").queue();
								return;
							}
							
							if(Main.server.isCampaining(sender))
							{
								event.reply("You can't change parties while campaigning!").queue();
								return;
							}
							
							// if(role == null)
							// {
							// Main.log.error("The political party role doesn't exist: {}", sender.getPoliticalParty());
							// event.reply("Huh. Couldn't find the role associated with your political party... left it anyways?").queue();
							// sender.setPoliticalParty(null);
							// Main.updateServerData();
							// return;
							// }
							
							// If this is the leader
							PoliticalParty party = sender.getPoliticalParty();
							// Should never be null...? right?
							Role role = guild.getRoleById(party.getRole());
							
							if(party.getLeaderID() == user.getIdLong())
							{
								// If the leader is the only one who remains
								if(Main.server.getPartyMembers(party).size() == 1)
								{
									// This might take a while
									event.deferReply().queue();
									
									Main.server.deletePartyAndChannels(party, guild).thenAccept(status ->
									{
										event.getHook().sendMessage(status ? "Party deleted" : Main.ERROR_MSG).queue(null, failure ->
										{
											Main.log.warn("Failed to return a response to the leave party command... maybe they called the command in the channel that was deleted. Channel: {}", event.getChannel(), failure);
										});
									}).exceptionally(e ->
									{
										Main.log.error("Failed to delete party", e);
										event.getHook().sendMessage(Main.ERROR_MSG).queue();
										return null;
									});
									
									return;
								}
								else
								{
									event.reply("Transfer power to one of your disciples first!").queue();
									return;
								}
							}
							else
							{
								sender.setPoliticalParty(null);
								Main.updateServerData();
								
								guild.removeRoleFromMember(user, role).queue(done ->
								{
									event.reply("Left <@&" + role.getId() + ">").setAllowedMentions(Set.of()).queue();
									Main.updateServerData();
								}, e ->
								{
									Main.log.error("Failed to leave party", e);
									event.reply(Main.ERROR_MSG).queue();
								});
							}
							
							break;
						}
						case "info":
						{
							// Should never be null...? right?
							Role role = event.getOption("party").getAsRole();
							
							// If the role mentioned is an actual political party
							if(!Main.server.isParty(role))
							{
								event.reply("That role isn't a political party").queue();
								return;
							}
							
							List<ServerMember> members = Main.server.getPartyMembers(Main.server.getParty(role.getIdLong()));
							StringBuilder description = new StringBuilder("**Party members** (" + members.size() + " total):");
							
							for(int i = 0; i < Math.min(15, members.size()); i++)
							{
								description.append("\n- <@" + members.get(i).getID() + ">");
							}
							
							if(members.size() > 15)
								description.append("\n... and ").append(members.size() - 15).append(" more");
							
							PoliticalParty party = sender.getPoliticalParty();
							List<Long> blacklist = new ArrayList<Long>(party.getBlacklist());
							
							// If we have banned members
							if(!blacklist.isEmpty())
							{
								description.append("\n\n**Banned members** (" + blacklist.size() + " total):");
								
								for(int i = 0; i < Math.min(15, blacklist.size()); i++)
								{
									description.append("\n- <@" + blacklist.get(i) + ">");
								}
								
								if(blacklist.size() > 15)
									description.append("\n... and ").append(blacklist.size() - 15).append(" more");
							}
							
							// Leader is guaranteed to not be null at this point
							EmbedBuilder builder = new EmbedBuilder();
							builder.setColor(role.getColor());
							builder.setTitle(role.getName());
							builder.setDescription(description);
							
							// In case the leader left the party (this should be picked up by a party deleter function)
							guild.retrieveMemberById(Main.server.getParty(role.getIdLong()).getLeaderID()).queue(leader ->
							{
								String leaderName = leader != null ? leader.getEffectiveName() : "Unknown";
								
								builder.setFooter("Led by " + MarkdownSanitizer.escape(leaderName), leader.getEffectiveAvatarUrl());
								event.replyEmbeds(builder.build()).queue();
							}, e ->
							{
								Main.log.error("Failed to get party info", e);
								event.reply(Main.ERROR_MSG).queue();
							});
							
							break;
						}
					}
				}
				
				// Exit party loop
				break;
			}
			case "naturalize":
			{
				Member member = event.getOption("user").getAsMember();
				
				// This is something we need to check because you can put in foreign users apparently
				if(member == null)
				{
					event.reply("Unknown member").queue();
					break;
				}
				
				// Check if it's a bot
				if(isBot(member))
				{
					event.reply("Bots don't have rights :robot:").queue();
					break;
				}
				
				// Check if we already have the citizen role
				if(Main.server.isNaturalized(member))
				{
					event.reply("This user is already naturalized").queue();
					break;
				}
				
				Main.server.beginPoll(event, new NaturalizePoll(jda.getTextChannelById(Main.VOTING_BOOTH), member));
				break;
			}
			case "campaign":
			{
				// Don't allow new lines
				// Do not use escape here because \n would look ugly as hell
				String slogan = MarkdownSanitizer.sanitize(event.getOption("slogan").getAsString()).replace('\n', ' ').replace('\t', ' ');
				
				if(Main.server.isPresident(sender))
				{
					if(Main.server.isLastTerm())
					{
						event.reply("You cannot be elected President for more than two terms at a time.").queue();
						return;
					}
					else
					{
						event.reply("The President automatically runs for re-election once voting begins.").queue();
						return;
					}
				}
				
				// You can only campaign when the presidential vote poll is live
				if(!Main.server.isElectionActive())
				{
					float daysRemaining = Main.server.millisRemainingInTerm() / 8.64e+7f;
					event.reply("Polls for the **" + Server.ordinal(Main.server.getPresidentialCount() + 1) + " Presidential Election** open **" + getExactTime(System.currentTimeMillis() + Main.server.millisRemainingInTerm() - Server.PRESIDENTIAL_VOTE_TIME) + " EST**. The President has " + (int) (daysRemaining) + " day" + ((int) daysRemaining != 1 ? "s" : "") + " and " + (int) (daysRemaining % 1 * 24) + " hours left in office. You will be notified in <#" + Main.VOTING_BOOTH + "> when the election begins.").queue();
				}
				else if(Main.server.getCandidates().size() == 10)
				{
					event.reply("There are too many candidates running for office. Only 10 at a time.").queue();
				}
				else if(slogan.length() > Math.min(200, OptionData.MAX_STRING_OPTION_LENGTH))
				{
					// Just in case it changes but totally unnecessary
					event.reply("Slogan must be less than " + Math.min(200, OptionData.MAX_STRING_OPTION_LENGTH) + " characters.").setEphemeral(true).queue();
				}
				else
				{
					// Check if already campaigning
					for(Candidate candidate : Main.server.getCandidates())
					{
						if(candidate.getID() == sender.getID())
						{
							event.reply("You're already campaigning!").queue();
							return;
						}
					}
					
					PoliticalParty party = sender.getPoliticalParty();
					
					if(party == null)
					{
						event.reply("You need to join a party first").queue();
						return;
					}
					
					Main.server.getCandidates().add(new Candidate(sender, Main.server.getNextCandidateSlot(), slogan));
					
					// Add reactions
					for(int i = 0; i < Main.server.getCandidates().size(); i++)
					{
						if(i != 9)
						{
							Main.server.getPresidentialVote(jda).addReaction(Emoji.fromUnicode("U+3" + (i + 1) + "U+fe0fU+20e3")).queue();
						}
						else
						{
							Main.server.getPresidentialVote(jda).addReaction(Emoji.fromUnicode("U+1f51f")).queue();
						}
					}
					
					Main.server.updatePresidentialVote(jda);
					event.reply("You are now campaigning! Check the Presidential Voting poll in <#" + Main.VOTING_BOOTH + ">.").queue();
				}
				
				return;
			}
			case "slogan":
			{
				String content = MarkdownSanitizer.sanitize(event.getOption("slogan").getAsString());
				
				if(Main.server.isPresident(sender))
				{
					Main.server.setPresidentialSlogan(content);
					event.reply("Updated your slogan, Mr. President" + Main.server.getPresidentialVote(jda) == null ? ". You will see it during the next election" : "").queue();
					return;
				}
				
				if(Main.server.getPresidentialVote(jda) == null)
				{
					event.reply("There is no active presidential election").queue();
					return;
				}
				// Check if already campaigning
				for(Candidate candidate : Main.server.getCandidates())
				{
					if(candidate.getID() == sender.getID())
					{
						candidate.setSlogan(content);
						Main.server.updatePresidentialVote(jda);
						event.reply("Updated your slogan to \"" + content + "\"").queue();
						return;
					}
				}
				
				event.reply("You're not campaigning! Use " + Main.getCommandReference("campaign") + " to register").queue();
				return;
			}
			case "next-election":
			{
				if(Main.server.getPresidentialVote(jda) != null)
				{
					event.reply("The current election will end at **" + getExactTime(System.currentTimeMillis() + Main.server.millisRemainingInTerm()) + " EST**.").queue();
				}
				else
				{
					event.reply("The next election opens on **" + getExactTime(System.currentTimeMillis() + Main.server.millisRemainingInTerm() - Server.PRESIDENTIAL_VOTE_TIME) + " EST**.").queue();
				}
				
				return;
			}
			case "propose":
			{
				String content = event.getOption("amendment").getAsString();
				// content = MarkdownSanitizer.escape(content); // escape, not sanitize. Allows people to type * instead of removing it
				
				// Add the poll
				Main.server.beginPoll(event, new ProposePoll(jda.getTextChannelById(Main.VOTING_BOOTH), content));
				break;
			}
			case "repeal":
			{
				int number = event.getOption("amendment-number").getAsInt();
				
				if(number < 1 || number > Main.server.getAmendments())
				{
					event.reply("Enter a number between 1 - " + Main.server.getAmendments()).setEphemeral(true).queue();
					break;
				}
				
				// Add the poll
				Main.server.beginPoll(event, new RepealPoll(jda.getTextChannelById(Main.VOTING_BOOTH), number));
				break;
			}
			case "impeach":
			{
				// Don't allow impeachment if it will overlap with the presidential vote
				ImpeachPoll poll = new ImpeachPoll(jda.getTextChannelById(Main.VOTING_BOOTH), event.getOption("reason").getAsString());
				
				if(Main.server.millisRemainingInTerm() - Server.PRESIDENTIAL_VOTE_TIME < poll.getVoteTime().toMillis())
				{
					if(Main.server.getPresidentialVote(jda) == null)
					{
						event.reply("Impeachment disabled. The polls open **" + getExactTime(System.currentTimeMillis() + Main.server.millisRemainingInTerm() - Server.PRESIDENTIAL_VOTE_TIME) + " EST.**").queue();
					}
					else
					{
						event.reply("Impeachment disabled. An election is active").queue();
					}
					
					break;
				}
				
				// Add the poll
				Main.server.beginPoll(event, poll);
				break;
			}
			// case "secret":
			// {
			// String word = event.getOption("word").getAsString().trim();
			// String response = event.getOption("response").getAsString().trim();
			//
			// DMain.server.addSecret(word, response);
			//
			// event.reply("\"" + word + "\" is now a secret command (will send " + response + ")").queue();
			// return;
			// }
			// case "all-secrets":
			// {
			// event.reply(DMain.server.getSecretCommands().keySet().stream().sorted().collect(Collectors.joining(", "))).queue();
			// return;
			// }
			// case "unsecret":
			// {
			// String word = event.getOption("word").getAsString();
			//
			// // If success
			// if(DMain.server.unsecret(word))
			// {
			// event.reply("Removed \"" + MarkdownSanitizer.sanitize(word) + "\" from secret commands").queue();
			// }
			// else
			// {
			// event.reply("\"" + MarkdownSanitizer.sanitize(word) + "\" isn't a secret command").queue();
			// }
			//
			// return;
			// }
			// case "resecret":
			// {
			// String word = event.getOption("word").getAsString();
			//
			// if(DMain.server.resecretSecret(word))
			// {
			// event.reply("Resecreted \"" + MarkdownSanitizer.sanitize(word) + "\"").queue();
			// }
			// else
			// {
			// event.reply("\"" + MarkdownSanitizer.sanitize(word) + "\" isn't an unsecreted command").queue();
			// }
			//
			// return;
			// }
			default:
			{
				Main.log.error("Unhandled command {}", event.getName());
				event.reply("This command is under construction :hammer: :construction:").queue();
				return;
			}
		}
	}
	
	private boolean isBot(Member member)
	{
		return member.getUser().isBot() || member.getUser().isSystem();
	}
	
	/**
	 * Don't prepend the HEX color with a number sign.
	 * 
	 * @param hex hex without number sign (e.g., FF0000)
	 * @return color
	 */
	@Nullable
	private Color validateHex(String hex)
	{
		Color color = null;
		hex = "#" + hex;
		
		try
		{
			color = Color.decode(hex);
		} catch(NumberFormatException e)
		{
			Main.log.warn("Can't parse user's color: {}", hex);
		}
		
		return color;
	}
	
	@Override
	public void onSlashCommandInteraction(SlashCommandInteractionEvent event)
	{
		// Handle any errors
		try
		{
			slashCommand(event);
		} catch(Throwable t)
		{
			if(!event.isAcknowledged())
				event.reply(Main.ERROR_MSG).queue();
			Main.log.error("An error occured in command handling", t);
		}
	}
	
	@Override
	public void onGuildMemberJoin(GuildMemberJoinEvent event)
	{
		// This will add back the citizen role if they were naturalized
		Main.log.info("{} joined the server. Naturalized: {}", event.getUser(), Main.server.isNaturalized(event.getMember()));
	}
	
	@Override
	public void onGuildMemberRemove(GuildMemberRemoveEvent event)
	{
		Main.server.removeMember(event.getJDA(), event.getUser().getIdLong());
		Main.log.info("{} ({}) left the server ", event.getUser().getEffectiveName(), event.getUser().getId());
	}
	
	@Override
	public void onSessionDisconnect(SessionDisconnectEvent event)
	{
		CloseCode code = event.getCloseCode();
		Main.log.info("DISCONNECTED! Close code: " + (code == null ? "null" : code.getCode() + ". Meaning: " + code.getMeaning()) + ". Closed by discord: " + event.isClosedByServer());
		lastDisconnect = System.currentTimeMillis();
	}
	
	@Override
	public void onException(ExceptionEvent event)
	{
		Main.log.error("JDA Exception! Response code: {}, logged: {}, cause: {}, #{}", event.getResponseNumber(), event.isLogged(), event.getCause(), event.getResponseNumber());
	}
	
	private String getExactTime(long time)
	{
		return new SimpleDateFormat("MM/dd/yyyy h:mm aa").format(new Date(time));
	}
}
