package democracy;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Map.Entry;
import java.util.concurrent.TimeUnit;

import com.google.gson.JsonElement;
import com.supasulley.utils.JsonUtils;

import net.dv8tion.jda.api.JDA;
import net.dv8tion.jda.api.entities.Guild;
import net.dv8tion.jda.api.entities.Message;
import net.dv8tion.jda.api.entities.MessageEmbed;
import net.dv8tion.jda.api.entities.Role;
import net.dv8tion.jda.api.entities.User;
import net.dv8tion.jda.api.entities.channel.ChannelType;
import net.dv8tion.jda.api.entities.channel.concrete.TextChannel;
import net.dv8tion.jda.api.entities.emoji.Emoji;
import net.dv8tion.jda.api.events.ExceptionEvent;
import net.dv8tion.jda.api.events.GatewayPingEvent;
import net.dv8tion.jda.api.events.guild.member.GuildMemberJoinEvent;
import net.dv8tion.jda.api.events.guild.member.GuildMemberRemoveEvent;
import net.dv8tion.jda.api.events.interaction.command.SlashCommandInteractionEvent;
import net.dv8tion.jda.api.events.message.MessageReceivedEvent;
import net.dv8tion.jda.api.events.session.SessionDisconnectEvent;
import net.dv8tion.jda.api.events.session.SessionResumeEvent;
import net.dv8tion.jda.api.interactions.commands.build.OptionData;
import net.dv8tion.jda.api.requests.CloseCode;
import net.dv8tion.jda.api.utils.MarkdownSanitizer;

public class EventHandler extends GenericEventHandler {
	
	// 1 minute per tick
	private static final long TICK_TIME = 60000;
	private long lastTick;
	
	public EventHandler(JDA jda)
	{
		super(jda);
		
		// Check during downtime if there's been any poll results generated by Discord
		// Limited by pagination but only grabbing 100 max should suffice
		jda.getGuildById(DMain.SERVER_ID).getTextChannelById(DMain.VOTING_BOOTH).getHistoryFromBeginning(100).queue(history ->
		{
			history.getRetrievedHistory().forEach(message ->
			{
				// Check for polls
				DMain.server.checkMessageForPollResult(message);
			});
		}, error -> DMain.log.error("Failed to collect messages on startup for poll checking", error));
	}
	
	/**
	 * Ticks the server object and verifies server data is kept up to date.
	 */
	@Override
	public void onGatewayPing(GatewayPingEvent event)
	{
		if(System.currentTimeMillis() - lastTick > TICK_TIME)
		{
			// Check if server data changed
			try {
				JsonElement data = JsonUtils.parse(DMain.readServerData());
				JsonElement current = JsonUtils.parse(DMain.server.toString());
				
				if(!data.equals(current))
				{
					DMain.log.info("Stored server data:\n{}\nServer object data:\n{}", data, current);
					throw new IllegalStateException("Stored server data and server object data do not match");
				}
			} catch(Exception e) {
				DMain.log.error("JSON data does not match! You failed to update the server data somewhere", e);
				DMain.updateServerData();
			}
			
			lastTick = System.currentTimeMillis();
			DMain.server.tick(event.getJDA());
		}
	}
	
	private void slashCommand(SlashCommandInteractionEvent event)
	{
		if(!event.isFromGuild())
		{
			event.reply("DM commands are not supported. Use " + DMain.BOT_NAME + " in Discordias.").setEphemeral(true).queue();
			return;
		}
		
		JDA jda = event.getJDA();
		
		// Message content
		User user = event.getUser();
		Guild guild = event.getGuild();
		
		// Don't acknowledge if we're in test channel
		if(!DMain.inIDE && event.getChannel().getIdLong() == DMain.TEST_CHANNEL)
		{
			DMain.log.info("Ignoring test channel command");
			return;
		}
		
		ServerMember sender = DMain.server.getMember(user);
		
		DMain.log.info("[SLASH COMMAND (" + guild.getId() + ", channel #" + event.getChannel().getId() + ") - '" + user.getName() + "']: \"" + event.getCommandString() + "\"");
		
		switch(event.getFullCommandName())
		{
			case "campaign":
			{
				// Don't allow new lines
				String slogan = MarkdownSanitizer.sanitize(event.getOption("slogan").getAsString()).replace('\n', ' ').replace('\t', ' ');
				
				if(DMain.server.isPresident(sender))
				{
					if(DMain.server.isLastTerm())
					{
						event.reply("You cannot be elected President for more than two terms at a time.").queue();
						return;
					}
					else
					{
						event.reply("The President automatically runs for re-election once voting begins.").queue();
						return;
					}
				}
				
				// You can only campaign when the presidential vote poll is live
				if(DMain.server.getPresidentialVote(jda) == null)
				{
					float daysRemaining = DMain.server.millisRemainingInTerm() / 8.64e+7f;
					event.reply("Polls for the **" + Server.ordinal(DMain.server.getPresidentialCount() + 1) + " Presidential Election** open " + getExactTime(System.currentTimeMillis() + DMain.server.millisRemainingInTerm() - Server.PRESIDENTIAL_VOTE_TIME) + " EST**. The President has " + (int) (daysRemaining) + " day" + ((int) daysRemaining != 1 ? "s" : "") + " and " + (int) (daysRemaining % 1 * 24) + " hours left in office. You will be notified in <#" + DMain.VOTING_BOOTH + "> when the election begins.").queue();
				}
				else if(DMain.server.getCandidates().size() == 10)
				{
					event.reply("There are too many candidates running for office. Only 10 at a time.").queue();
				}
				else if(slogan.length() > Math.min(200, OptionData.MAX_STRING_OPTION_LENGTH))
				{
					// Just in case it changes but totally unnecessary
					event.reply("Slogan must be less than " + Math.min(200, OptionData.MAX_STRING_OPTION_LENGTH) + " characters.").setEphemeral(true).queue();
				}
				else
				{
					// Check if already campaigning
					for(Candidate candidate : DMain.server.getCandidates())
					{
						if(candidate.getID() == sender.getID())
						{
							event.reply("You're already campaigning!").queue();
							return;
						}
					}
					
					Role party = event.getOption("party").getAsRole();
					DMain.server.getCandidates().add(new Candidate(DMain.server.getNextCandidateSlot(), user.getIdLong(), slogan, party));
					
					// Add reactions
					for(int i = 0; i < DMain.server.getCandidates().size(); i++)
					{
						if(i != 9)
						{
							DMain.server.getPresidentialVote(jda).addReaction(Emoji.fromUnicode("U+3" + (i + 1) + "U+fe0fU+20e3")).queue();
						}
						else
						{
							DMain.server.getPresidentialVote(jda).addReaction(Emoji.fromUnicode("U+1f51f")).queue();
						}
					}
					
					DMain.server.updatePresidentialVote(jda);
					event.reply("You are now campaigning! Check the Presidential Voting poll in <#" + DMain.VOTING_BOOTH + ">.").queue();
				}
				
				return;
			}
			case "slogan":
			{
				String content = MarkdownSanitizer.sanitize(event.getOption("slogan").getAsString());
				
				if(DMain.server.getPresidentialVote(jda) == null)
				{
					event.reply("There is no active presidential election").queue();
					return;
				}
				// Check if already campaigning
				for(Candidate candidate : DMain.server.getCandidates())
				{
					if(candidate.getID() == sender.getID())
					{
						candidate.setSlogan(content);
						DMain.server.updatePresidentialVote(jda);
						event.reply("Updated your slogan to \"" + content + "\"").queue();
						return;
					}
				}
				
				event.reply("You're not campaigning! Use " + DMain.getCommandReference("campaign") + " to register").queue();
				return;
			}
			case "next-election":
			{
				if(DMain.server.getPresidentialVote(jda) != null)
				{
					event.reply("The current election will end at **" + getExactTime(System.currentTimeMillis() + DMain.server.millisRemainingInTerm()) + " EST**.").queue();
				}
				else
				{
					event.reply("The next election opens on **" + getExactTime(System.currentTimeMillis() + DMain.server.millisRemainingInTerm() - Server.PRESIDENTIAL_VOTE_TIME) + " EST**.").queue();
				}
				
				return;
			}
			case "propose":
			{
				String content = event.getOption("amendment").getAsString();
				
				// Add the poll
				DMain.server.beginPoll(event, new ProposePoll(jda.getTextChannelById(DMain.VOTING_BOOTH), content));
				break;
			}
			case "repeal":
			{
				int number = event.getOption("amendment-number").getAsInt();
				
				if(number < 1 || number > DMain.server.getAmendments())
				{
					event.reply("Enter a number between 1 - " + DMain.server.getAmendments()).setEphemeral(true).queue();
					break;
				}
				
				// Add the poll
				DMain.server.beginPoll(event, new RepealPoll(jda.getTextChannelById(DMain.VOTING_BOOTH), number));
				break;
			}
			case "impeach":
			{
				// Don't allow impeachment if it will overlap with the presidential vote
				ImpeachPoll poll = new ImpeachPoll(jda.getTextChannelById(DMain.VOTING_BOOTH), event.getOption("reason").getAsString());
				
				if(DMain.server.millisRemainingInTerm() - Server.PRESIDENTIAL_VOTE_TIME < poll.getVoteTime().toMillis())
				{
					event.reply("Impeachment disabled. The polls open **" + getExactTime(System.currentTimeMillis() + DMain.server.millisRemainingInTerm() - Server.PRESIDENTIAL_VOTE_TIME) + " EST.**").queue();
					break;
				}
				
				// Add the poll
				DMain.server.beginPoll(event, poll);
				break;
			}
			case "secret":
			{
				String word = event.getOption("word").getAsString().trim();
				String response = event.getOption("response").getAsString().trim();
				
				DMain.server.addSecret(word, response);
				
				event.reply("\"" + word + "\" is now a secret command (will send " + response + ")").queue();
				return;
			}
			case "unsecret":
			{
				String word = event.getOption("word").getAsString();
				
				// If success
				if(DMain.server.unsecret(word))
				{
					event.reply("Removed \"" + MarkdownSanitizer.sanitize(word) + "\" from secret commands").queue();
				}
				else
				{
					event.reply("\"" + MarkdownSanitizer.sanitize(word) + "\" isn't a secret command").queue();
				}
				
				return;
			}
			case "resecret":
			{
				String word = event.getOption("word").getAsString();
				
				if(DMain.server.resecretSecret(word))
				{
					event.reply("Resecreted \"" + MarkdownSanitizer.sanitize(word) + "\"").queue();
				}
				else
				{
					event.reply("\"" + MarkdownSanitizer.sanitize(word) + "\" isn't an unsecreted command").queue();
				}
				
				return;
			}
			default:
			{
				DMain.log.error("Unhandled command {}", event.getName());
				event.reply("This command is under construction :hammer: :construction:").queue();
				return;
			}
		}
	}
	
	@Override
	public void onSlashCommandInteraction(SlashCommandInteractionEvent event)
	{
		// Handle any errors
		try {
			slashCommand(event);
		} catch(Throwable t) {
			if(!event.isAcknowledged())
				event.reply(DMain.ERROR_MSG).queue();
			DMain.log.error("An error occured in command handling", t);
		}
	}
	
	@Override
	public void onGuildMessageReceived(MessageReceivedEvent event)
	{
		DMain.server.checkMessageForPollResult(event.getMessage());
		
		// BEYOND THIS POINT IS ONLY SECRET COMMANDS
		if(event.getAuthor().isBot() || DMain.SERVER_ID != event.getGuild().getIdLong() || !event.isFromType(ChannelType.TEXT))
			return;
		
		// Get user
		TextChannel channel = event.getChannel().asTextChannel();
		
		// Handle server command requests
		String message = event.getMessage().getContentDisplay().replaceAll("\n", "");
		
		// Secret commands
		if(channel.getParentCategory() == null || channel.getParentCategory().getIdLong() == DMain.THE_WHITE_HOUSE_CATEGORY || channel.getParentCategory().getIdLong() == DMain.MAGNA_FARTA_CATEGORY)
			return;
		if(message.contains("http"))
			return;
			
		// boolean canReact = eventMessage.getGuild().getSelfMember().hasPermission(Permission.MESSAGE_ADD_REACTION);
		// int numReacts = 0;
		StringBuilder builder = new StringBuilder();
		Map<String, String> commands = new HashMap<String, String>();
		
		// For each key (word)
		for(String key : DMain.server.getSecretCommands().keySet())
		{
			// If it CONTAINS, not equals
			if(message.toLowerCase().contains(key.toLowerCase()))
			{
				String[] values = DMain.server.getSecretCommands().get(key).split("\n");
				// Pick random link
				String value = values[(int) (Math.random() * values.length)];
				
				// +1 for break character
				if(builder.length() + value.length() + 1 > Message.MAX_CONTENT_LENGTH)
					break;
				
				// Append command
				builder.append(value + "\n");
				commands.put(key, value);
				//
				// if(canReact && numReacts < Message.MAX_REACTIONS)
				// {
				// numReacts++;
				// eventMessage.addReaction(Emoji.fromUnicode(unicode)).queue();
				// }
			}
		}
		
		// This can happen believe it or not (user can make a poll and then this blows tf up)
		if(builder.toString().isEmpty())
			return;
		
		event.getChannel().sendMessage(builder.toString()).queue(queued ->
		{
			// Wait before getting the new message
			event.getChannel().retrieveMessageById(queued.getId()).queueAfter(3, TimeUnit.SECONDS, success ->
			{
				boolean modified = false;
				
				// For each secret
				for(Entry<String, String> set : commands.entrySet())
				{
					String key = set.getKey();
					String link = set.getValue();
					
					// If that secret is a link (trying to be an embed)
					if(link.contains("http"))
					{
						boolean found = false;
						
						// Check if that link actually embedded properly
						for(MessageEmbed embed : success.getEmbeds())
						{
							String url = embed.getUrl();
							
							if(url.equals(link))
							{
								found = true;
								break;
							}
						}
						
						if(!found)
						{
							modified = true;
							DMain.log.info("Removing {} from secret commands. Embed didn't work at {}", key, link);
							DMain.server.getSecretCommands().remove(key);
							
							// If it was just one secret command, just delete the message
							if(commands.size() == 1)
							{
								success.delete().queue();
							}
						}
					}
				}
				
				if(modified)
				{
					DMain.updateServerData();
				}
			});
		});
	}
	
	@Override
	public void onGuildMemberJoin(GuildMemberJoinEvent event)
	{
		DMain.log.info(event.getUser().getName() + " " + event.getUser().getIdLong() + " joined!");
	}
	
	@Override
	public void onGuildMemberRemove(GuildMemberRemoveEvent event)
	{
		DMain.server.removeMember(event.getJDA(), event.getUser().getIdLong());
		DMain.log.info("{} ({}) left the server ", event.getMember().getEffectiveName(), event.getMember().getId());
	}
	
	@Override
	public void onSessionDisconnect(SessionDisconnectEvent event)
	{
		CloseCode code = event.getCloseCode();
		DMain.log.info("DISCONNECTED! Close code: " + (code == null ? "null" : code.getCode() + ". Meaning: " + code.getMeaning()) + ". Closed by discord: " + event.isClosedByServer());
	}
	
	@Override
	public void onSessionResume(SessionResumeEvent event)
	{
		DMain.log.info("Reconnected!");
	}
	
	@Override
	public void onException(ExceptionEvent event)
	{
		DMain.log.error("JDA Exception! Response code: {}, logged: {}, cause: {}, #{}", event.getResponseNumber(), event.isLogged(), event.getCause(), event.getResponseNumber());
	}
	
	private String getExactTime(long time)
	{
		return new SimpleDateFormat("MM/dd/yyyy h:mm aa").format(new Date(time));
	}
}
