package democracy;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Map.Entry;
import java.util.concurrent.TimeUnit;

import net.dv8tion.jda.api.JDA;
import net.dv8tion.jda.api.entities.Guild;
import net.dv8tion.jda.api.entities.Message;
import net.dv8tion.jda.api.entities.MessageEmbed;
import net.dv8tion.jda.api.entities.MessageType;
import net.dv8tion.jda.api.entities.Role;
import net.dv8tion.jda.api.entities.User;
import net.dv8tion.jda.api.entities.channel.concrete.TextChannel;
import net.dv8tion.jda.api.entities.emoji.Emoji;
import net.dv8tion.jda.api.events.ExceptionEvent;
import net.dv8tion.jda.api.events.guild.member.GuildMemberJoinEvent;
import net.dv8tion.jda.api.events.guild.member.GuildMemberRemoveEvent;
import net.dv8tion.jda.api.events.interaction.command.SlashCommandInteractionEvent;
import net.dv8tion.jda.api.events.message.MessageReceivedEvent;
import net.dv8tion.jda.api.events.session.SessionDisconnectEvent;
import net.dv8tion.jda.api.events.session.SessionResumeEvent;
import net.dv8tion.jda.api.interactions.commands.build.OptionData;
import net.dv8tion.jda.api.requests.CloseCode;
import net.dv8tion.jda.api.utils.MarkdownSanitizer;

public class EventHandler extends GenericEventHandler {
	
	public EventHandler(JDA jda)
	{
		super(jda);
		
		// Check during downtime if there's been any poll results generated by Discord
		jda.getGuildById(DMain.SERVER_ID).getTextChannelById(DMain.VOTING_BOOTH).getHistoryFromBeginning(100).queue(history ->
		{
			history.getRetrievedHistory().forEach(message ->
			{
				// Check for polls
				checkMessageForPollResult(message);
			});
		}, DMain::error);
	}
	
	/**
	 * Should be called with long intervals (i.e. 30 seconds min)
	 */
	public void tick()
	{
		// Tick polls
		// I don't think we need to worry about deletes here
//		Iterator<Poll> iterator = DMain.server.getPolls().iterator();
//		
//		while(iterator.hasNext())
//		{
//			Poll sample = iterator.next();
//			
//			// 1 day
//			if(System.currentTimeMillis() - sample.getStartTime() >= 8.64e+7)
//			{
//				DMain.log("ENDING THE POLL!");
//				sample.endPoll(jda.getGuildById(DMain.SERVER_ID).getTextChannelById(DMain.VOTING_BOOTH).retrieveMessageById(sample.getMessageID()).complete());
//				iterator.remove();
//			}
//		}
		
		DMain.server.tick(jda);
	}
	
	public ServerMember getMember(User user)
	{
		// Now that we have the server, search for member within server
		for(ServerMember member : DMain.server.getMembers())
		{
			// If the user already exists, move to front of list
			if(member.isUser(user.getIdLong()))
			{
				return member;
			}
		}
		
		// If we couldn't find user / server, the ServerMember is new
		ServerMember initMember = new ServerMember(user.getIdLong());
		DMain.server.addMember(initMember);
		return initMember;
	}
	
	private void slashCommand(SlashCommandInteractionEvent event)
	{
		if(!event.isFromGuild())
		{
			event.reply("DM commands are not supported. Please use " + DMain.BOT_NAME + " in your server.").setEphemeral(true).queue();
			return;
		}
		
		// Message content
		User user = event.getUser();
		Guild guild = event.getGuild();
		
		ServerMember sender = getMember(user);
		
		DMain.log("[SLASH COMMAND (" + guild.getId() + ", channel #" + event.getChannel().getId() + ") - '" + user.getName() + "']: \"" + event.getCommandString() + "\"");
		
		switch(event.getFullCommandName())
		{
			case "campaign":
			{
				String slogan = MarkdownSanitizer.sanitize(event.getOption("slogan").getAsString());
				
				if(DMain.server.isPresident(sender))
				{
					if(DMain.server.isLastTerm())
					{
						event.reply("You cannot be elected President for more than two terms at a time.").queue();
						return;
					}
					else
					{
						event.reply("The President automatically runs for re-election once voting begins.").queue();
						return;
					}
				}
				
				// You can only campaign when the presidential vote poll is live
				if(DMain.server.getPresidentialVote(jda) == null)
				{
					float daysRemaining = DMain.server.millisRemainingInTerm() / 8.64e+7f;
					event.reply("The Presidential Election is active during the last 3 days of the President's term (last day is " + new SimpleDateFormat("MM/dd/yyyy").format(new Date(System.currentTimeMillis() + DMain.server.millisRemainingInTerm())) + "). The President has " + (int) (daysRemaining) + " day" + ((int) daysRemaining != 1 ? "s" : "") + " and " + (int) (daysRemaining % 1 * 24) + " hours left in office. You will be notified in <#" + DMain.VOTING_BOOTH + "> when the election begins.").queue();
				}
				else if(DMain.server.getCandidates().size() == 10)
				{
					event.reply("There are too many candidates running for office. Only 10 at a time.").queue();
				}
				else if(slogan.length() > Math.min(200, OptionData.MAX_STRING_OPTION_LENGTH))
				{
					// Just in case it changes but totally unnecessary
					event.reply("Slogan must be less than " + Math.min(200, OptionData.MAX_STRING_OPTION_LENGTH) + " characters.").setEphemeral(true).queue();
				}
				else
				{
					// Check if already campaigning
					for(Candidate candidate : DMain.server.getCandidates())
					{
						if(candidate.getID() == sender.getID())
						{
							event.reply("You're already campaigning!").queue();
							return;
						}
					}
					
					Role party = event.getOption("party").getAsRole();
					DMain.server.getCandidates().add(new Candidate(DMain.server.getNextCandidateSlot(), user.getIdLong(), slogan, party));
					
					// Add reactions
					for(int i = 0; i < DMain.server.getCandidates().size(); i++)
					{
						if(i != 9)
						{
							DMain.server.getPresidentialVote(jda).addReaction(Emoji.fromUnicode("U+3" + (i + 1) + "U+fe0fU+20e3")).queue();
						}
						else
						{
							DMain.server.getPresidentialVote(jda).addReaction(Emoji.fromUnicode("U+1f51f")).queue();
						}
					}
					
					DMain.server.updatePresidentialVote(jda);
					event.reply("You are now campaigning! Check the Presidential Voting poll in <#" + DMain.VOTING_BOOTH + ">.").queue();
				}
				
				return;
			}
			case "slogan":
			{
				String content = MarkdownSanitizer.sanitize(event.getOption("slogan").getAsString());
				
				if(DMain.server.getPresidentialVote(jda) == null)
				{
					event.reply("There is no active presidential election").queue();
					return;
				}
				// Check if already campaigning
				for(Candidate candidate : DMain.server.getCandidates())
				{
					if(candidate.getID() == sender.getID())
					{
						candidate.setSlogan(content);
						DMain.server.updatePresidentialVote(jda);
						event.reply("Updated your slogan to \"" + content + "\"").queue();
						return;
					}
				}
				
				event.reply("You're not campaigning! Use </campaign:" + DMain.getCommandByName("campaign").getId() + "> to register").queue();
				return;
			}
			case "next-election":
			{
				if(DMain.server.getPresidentialVote(jda) != null)
				{
					event.reply("The current election will end at **" + getExactTime(System.currentTimeMillis() + DMain.server.millisRemainingInTerm()) + " EST**.").queue();
				}
				else
				{
					event.reply("The next election opens on **" + getExactTime(System.currentTimeMillis() + DMain.server.millisRemainingInTerm() - Server.PRESIDENTIAL_VOTE_TIME) + " EST**.").queue();
				}
				
				return;
			}
			case "propose":
			{
				String content = event.getOption("amendment").getAsString();
				
				ProposePoll poll = new ProposePoll(jda.getTextChannelById(DMain.VOTING_BOOTH), content);
				
				if(!sender.canPropose(poll))
				{
					event.reply("You cannot propose amendments this frequently.").setEphemeral(true).queue();
				}
				else
				{
					event.reply("Poll added!").queue();
					DMain.server.getPolls().add(poll);
					break;
				}
				
				return;
			}
			case "repeal":
			{
				int number = event.getOption("amendment-number").getAsInt();
				
				if(number < 1 || number > DMain.server.getAmendments())
				{
					event.reply("Enter a number between 1-" + DMain.server.getAmendments()).setEphemeral(true).queue();
					return;
				}
				
				RepealPoll poll = new RepealPoll(jda.getTextChannelById(DMain.VOTING_BOOTH), number);
				
				if(!sender.canPropose(poll))
				{
					event.reply("You cannot repeal amendments this frequently.").setEphemeral(true).queue();
				}
				else
				{
					event.reply("Poll added!").queue();
					DMain.server.getPolls().add(poll);
				}
				
				return;
			}
			case "secret":
			{
				String word = event.getOption("word").getAsString().trim();
				String response = event.getOption("response").getAsString().trim();
				
				DMain.server.addSecret(word, response);
				
				event.reply("\"" + word + "\" is now a secret command (will send " + response + ")").queue();
				return;
			}
			case "unsecret":
			{
				String word = event.getOption("word").getAsString();
				
				// If success
				if(DMain.server.removeSecret(word))
				{
					event.reply("Removed \"" + MarkdownSanitizer.sanitize(word) + "\" from secret commands").queue();
				}
				else
				{
					event.reply("\"" + MarkdownSanitizer.sanitize(word) + "\" isn't a secret command").queue();
				}
				
				return;
			}
			default:
			{
				System.err.println("Unhandled command " + event.getName());
				event.reply(DMain.ERROR_MSG).queue();
				return;
			}
		}
	}
	
	@Override
	public void onSlashCommandInteraction(SlashCommandInteractionEvent event)
	{
		// Handle any errors
		try {
			slashCommand(event);
		} catch(Throwable t) {
			if(!event.isAcknowledged())
				event.reply(DMain.ERROR_MSG).queue();
			DMain.error("An error occured in command handling", t);
		}
	}
	
	public void onGuildMessageReceived(MessageReceivedEvent event)
	{
		checkMessageForPollResult(event.getMessage());
		
		if(event.getAuthor().isBot() || DMain.SERVER_ID != event.getGuild().getIdLong())
			return;
		
		// Get user
		TextChannel channel = event.getChannel().asTextChannel();
		
		// Handle server command requests
		String message = event.getMessage().getContentDisplay().replaceAll("\n", "");
		
		// Secret commands
		if(channel.getParentCategory() == null || channel.getParentCategory().getIdLong() == DMain.THE_WHITE_HOUSE_CATEGORY || channel.getParentCategory().getIdLong() == DMain.MAGNA_FARTA_CATEGORY)
			return;
		if(message.contains("http"))
			return;
			
		// boolean canReact = eventMessage.getGuild().getSelfMember().hasPermission(Permission.MESSAGE_ADD_REACTION);
		// int numReacts = 0;
		StringBuilder builder = new StringBuilder();
		Map<String, String> commands = new HashMap<String, String>();
		
		// For each key (word)
		for(String key : DMain.server.getSecretCommands().keySet())
		{
			// If it CONTAINS, not equals
			if(message.toLowerCase().contains(key.toLowerCase()))
			{
				String[] values = DMain.server.getSecretCommands().get(key).split("\n");
				// Pick random link
				String value = values[(int) (Math.random() * values.length)];
				
				// +1 for break character
				if(builder.length() + value.length() + 1 > Message.MAX_CONTENT_LENGTH)
					break;
				
				// Append command
				builder.append(value + "\n");
				commands.put(key, value);
				//
				// if(canReact && numReacts < Message.MAX_REACTIONS)
				// {
				// numReacts++;
				// eventMessage.addReaction(Emoji.fromUnicode(unicode)).queue();
				// }
			}
		}
		
		// This can happen believe it or not (user can make a poll and then this blows tf up)
		if(builder.toString().isEmpty())
			return;
		
		event.getChannel().sendMessage(builder.toString()).queue(queued ->
		{
			// Wait before getting the new message
			event.getChannel().retrieveMessageById(queued.getId()).queueAfter(3, TimeUnit.SECONDS, success ->
			{
				// For each secret
				for(Entry<String, String> set : commands.entrySet())
				{
					String key = set.getKey();
					String secret = set.getValue();
					
					// If that secret is a link (trying to be an embed)
					if(secret.contains("http"))
					{
						boolean found = false;
						
						// Check if that link actually embedded properly
						for(MessageEmbed embed : success.getEmbeds())
						{
							String url = embed.getUrl();
							
							if(url.equals(secret))
							{
								found = true;
								break;
							}
						}
						
						if(!found)
						{
							DMain.log("Removing " + key + " from secret commands. Embed didn't work - " + secret);
							DMain.server.getSecretCommands().remove(key);
							
							// If it was just one secret command, just delete the message
							if(commands.size() == 1)
							{
								success.delete().queue();
							}
						}
					}
				}
			});
		});
	}
	
	private void checkMessageForPollResult(Message message)
	{
		long textChannel = message.getChannel().getIdLong();
		
		// Check if voting booth && it's something important
		if(textChannel == DMain.VOTING_BOOTH && message.getType() == MessageType.POLL_RESULT)
		{
			// If it's a poll result, it's assumed the following logic will work to grab the referenced poll
			long pollID = message.getMessageReference().getMessageIdLong();
			Iterator<Poll> iterator = DMain.server.getPolls().iterator();
			
			// If this message belongs to a poll, it's done
			for(Poll sample = null; iterator.hasNext() && (sample = iterator.next()).getMessageID() == pollID;)
			{
				// The poll is done
				DMain.log("Received poll end message");
				sample.endPoll(jda);
				iterator.remove();
				
				// Delete after a while
				message.delete().queueAfter(1, TimeUnit.DAYS);
			}
		}
	}
	
	@Override
	public void onGuildMemberJoin(GuildMemberJoinEvent event)
	{
		// Add into immigration
		event.getGuild().addRoleToMember(event.getMember(), DMain.IMMIGRANT).queue();
		DMain.server.addImmigrant(event.getMember().getIdLong());
		
		DMain.log(event.getUser().getName() + " " + event.getUser().getIdLong() + " joined!");
	}
	
	@Override
	public void onGuildMemberRemove(GuildMemberRemoveEvent event)
	{
		User user = event.getUser();
		Iterator<ServerMember> iterator = DMain.server.getMembers().iterator();
		
		while(iterator.hasNext())
		{
			ServerMember member = iterator.next();
			
			if(member.getID() == user.getIdLong())
			{
				DMain.sendToOperator(user.getName() + " left the server!");
				
				DMain.server.removeMember(member.getID());
				removeMember(member.getID());
				iterator.remove();
				
				return;
			}
		}
		
		DMain.log("Unlogged participant left the server? " + user.getName());
	}
	
	/**
	 * Remove this member from nomination
	 */
	public void removeMember(long id)
	{
		// If this was the president
		if(DMain.server.hasPresident() && id == DMain.server.getPresidentID())
		{
			DMain.sendToOperator("The President left the server!");
			
			try {
				DMain.server.impeachPresident(jda.getGuildById(DMain.SERVER_ID)).call();
			} catch(Exception e) {
				DMain.log(e);
			}
		}
		
		// Remove member from candidates
		Iterator<Candidate> iterator = DMain.server.getCandidates().iterator();
		
		while(iterator.hasNext())
		{
			Candidate member = iterator.next();
			
			if(member.getID() == id)
			{
				DMain.log("Removing candidate from running");
				iterator.remove();
				
				// Remove the reaction that belonged to it
				DMain.server.getPresidentialVote(jda).getReaction(Emoji.fromUnicode(DMain.server.slotToReaction(member.getSlot()))).removeReaction().queue();
				DMain.server.updatePresidentialVote(jda);
				return;
			}
		}
	}
	
	@Override
	public void onSessionDisconnect(SessionDisconnectEvent event)
	{
		CloseCode code = event.getCloseCode();
		DMain.log("DISCONNECTED! Close code: " + (code == null ? "null" : code.getCode() + ". Meaning: " + code.getMeaning()) + ". Closed by discord: " + event.isClosedByServer());
	}
	
	@Override
	public void onSessionResume(SessionResumeEvent event)
	{
		DMain.log("Reconnected!");
	}
	
	@Override
	public void onException(ExceptionEvent event)
	{
		DMain.log("JDA Exception! Response code: " + event.getResponseNumber() + ". Logged: " + event.isLogged() + ". Cause: " + event.getCause());
	}
	
	private String getExactTime(long time)
	{
		return new SimpleDateFormat("MM/dd/yyyy h:mm aa").format(new Date(time));
	}
}
