name: Build DemocracyBot

on:
  workflow_dispatch: # !update in the bot handles this

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '22' # Dbot uses java 11, but build.gradle will make it behave

      # Weeve activities
      - name: Build weeve
        run: |
          git clone --recursive https://github.com/FreshSupaSulley/weeve.git
          cd weeve
          ./gradlew build
          cd ..
          mkdir -p libs
          cp weeve/build/libs/weeve.jar libs/weeve.jar

      - name: Create gradle.properties for tokens
        run: |
          # Weeve (yall can know my discord acc thats cool)
          echo "token=${{ secrets.WEEVE }}" >> gradle.properties
          echo "test_token=${{ secrets.OBAMA_BOT }}" >> gradle.properties
          echo "owner_id=276886864525262849" >> gradle.properties
          echo "notify_errors=true" >> gradle.properties
          # Dbot
          echo "democracy=${{ secrets.DEMOCRACY }}" >> gradle.properties
          echo "github_access_token=${{ secrets.GHAC }}" >> gradle.properties

      - name: Build jar
        run: |
          ./gradlew build

        # I hope no one can see this
      - name: Upload JAR as private artifact
        uses: actions/upload-artifact@v4
        with:
          name: DemocracyBot
          path: build/libs/*.jar

      - name: Notify DemocracyBot
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"content": "${{ github.run_id }}"}' \
          ${{ secrets.DISCORDIAS_WEBHOOK }}
      # - name: Create GitHub Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: build/libs/*.jar
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this one is built-in
